import type { Language } from "../config.js";
import type { Certainty, Confidence, Severity, SkipReason } from "../types.js";

type Dict = Record<Language, string>;

const pick = (dict: Dict, lang: Language): string => dict[lang];

export const MESSAGES = {
  reportTitle: { zh: "代码评审报告", en: "Code Review Report" },
  adoptableHeading: { zh: "可直接采纳（有确定性证据）", en: "Directly adoptable (backed by deterministic evidence)" },
  referenceHeading: { zh: "仅供参考（模型推断）", en: "For reference (model reasoning)" },
  noFindings: { zh: "本次评审没有发现需要报告的问题。", en: "This review found nothing worth reporting." },
  summaryHeading: { zh: "概览", en: "Summary" },
  evidenceHeading: { zh: "证据", en: "Evidence" },
  certaintyPrefix: { zh: "模型自评：", en: "model says: " },
  suggestionHeading: { zh: "建议改法", en: "Suggested change" },
  traceLabel: { zh: "追踪", en: "Trace" },
  appendixHeading: { zh: "附录", en: "Appendix" },
  spendHeading: { zh: "花费", en: "Spend" },
  skippedHeading: { zh: "跳过的文件", en: "Skipped files" },
  budgetEventsHeading: { zh: "预算事件", en: "Budget events" },
  redactionHeading: { zh: "脱敏统计", en: "Redaction summary" },
  redactionNote: {
    zh: "以下内容在发送给模型之前已被替换为占位符，原值从未离开本机。",
    en: "These were replaced with placeholders before anything was sent to a model; the original values never left this machine.",
  },
  partialWarning: {
    zh: "**预算已耗尽，本报告为部分结果。** 未评审的文件仍然跑过了零成本的确定性检查。提高 `--budget` 后重跑即可从断点继续。",
    en: "**The budget ran out; these are partial results.** Files that were not reviewed still went through the zero-cost deterministic checks. Re-run with a higher `--budget` to continue from the checkpoint.",
  },
  generatedBy: { zh: "由 code-review 生成", en: "Generated by code-review" },
  filesReviewed: { zh: "已评审文件", en: "Files reviewed" },
  modelsUsed: { zh: "使用的模型", en: "Models used" },
  postedComment: {
    zh: "本条评论由 code-review 自动生成。",
    en: "This comment was generated automatically by code-review.",
  },
} satisfies Record<string, Dict>;

export function t(key: keyof typeof MESSAGES, lang: Language): string {
  return pick(MESSAGES[key], lang);
}

export function severityLabel(severity: Severity, lang: Language): string {
  const labels: Record<Severity, Dict> = {
    blocker: { zh: "阻断", en: "blocker" },
    major: { zh: "重要", en: "major" },
    minor: { zh: "次要", en: "minor" },
    nit: { zh: "细节", en: "nit" },
  };
  return pick(labels[severity], lang);
}

export function confidenceLabel(confidence: Confidence, lang: Language): string {
  const labels: Record<Confidence, Dict> = {
    adoptable: { zh: "可直接采纳", en: "adoptable" },
    reference: { zh: "仅供参考", en: "reference" },
  };
  return pick(labels[confidence], lang);
}

/**
 * The model's own reading, worded so it cannot be mistaken for the tier.
 *
 * "高置信度" next to "仅供参考" would read as a contradiction and invite exactly
 * the promotion the tiers exist to prevent, so this vocabulary stays away from
 * the word: what the model has is a degree of sureness, not a confidence level.
 */
export function certaintyLabel(certainty: Certainty, lang: Language): string {
  const labels: Record<Certainty, Dict> = {
    certain: { zh: "确定", en: "sure" },
    likely: { zh: "多半", en: "likely" },
    unsure: { zh: "拿不准", en: "unsure" },
  };
  return pick(labels[certainty], lang);
}

export function skipLabel(reason: SkipReason, lang: Language): string {
  const labels: Record<SkipReason, Dict> = {
    binary: { zh: "二进制文件", en: "binary file" },
    generated: { zh: "生成/锁文件", en: "generated or lock file" },
    triage: { zh: "分诊阶段判定风险低", en: "deprioritized during triage" },
    budget: { zh: "预算耗尽", en: "budget exhausted" },
    empty: { zh: "无可评审内容", en: "nothing to review" },
  };
  return pick(labels[reason], lang);
}
